x

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -52,13 +52,20 @@ jobs:
           if: matrix.cfg.skip == false
           run: | 
             cd /project
-            if [[ $GITHUB_REF_TYPE == "branch" ]]; then
-              export BRANCH="master"
+            if [[ $GITHUB_REF_TYPE == "tag" ]]; then
+                export BRANCH="master"
             else
-              export BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
+                export BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
             fi
+
             echo "Fetching code from branch $BRANCH"
-            git clone --single-branch --depth 1 --branch $BRANCH $GIT_REPO
+
+            if git clone --single-branch --depth 1 --branch "$BRANCH" "$GIT_REPO"; then
+                echo "Code fetched successfully."
+            else
+                echo "Failed to fetch code. Check the repository and branch settings."
+                exit 1
+            fi
             
             ls /home/docker
         - name: "Set version"
