ci: fix

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -52,7 +52,21 @@ jobs:
         - name: "Fetch code" 
           run: | 
             cd /project
-            git clone --single-branch --depth 1 --branch master $GIT_REPO
+            if [[ $GITHUB_REF_TYPE == "tag" ]]; then
+                export BRANCH="master"
+            else
+                export BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
+            fi
+
+            echo "Fetching code from branch $BRANCH"
+
+            if git clone --single-branch --depth 1 --branch "$BRANCH" "$GIT_REPO"; then
+                echo "Code fetched successfully."
+            else
+                echo "Failed to fetch code. Check the repository and branch settings."
+                exit 1
+            fi
+
             ls /home/docker
         - name: "Set version"
           run: |
